### PR TITLE
Add support for SSH keys

### PR DESCRIPTION
**Pull request by rstacruz**
This allows you to deploy private GitHub repositories: #11.

```
docker run \
  -v (pwd)/id_rsa:/keys/id_rsa \
  -e GIT_REPO=git@github.com:private/repo.git \
  -it --rm --privileged tutum/builder ...
```

### CODE REVIEW

**Comment by fermayo** [comment]
Thanks for this - however, could we make it so it's an environment variable instead of relying on a file mount from the host?

**Comment by rstacruz** [comment]
i thought of that too but an SSH key is typically 27 lines (1.6kb) long... a little cumbersome to attach to an env var.

**Comment by rstacruz** [comment]
are you okay with where it's mounted, though? `/keys/id_rsa`? or would you prefer it to be in `/id_rsa`?

**Comment by fermayo** [comment]
It's not that cumbersome. You can just do `-e SSK_KEY="$(awk 1 ORS='\\n' ~/.ssh/id_rsa)"` and it gets injected nicely, with zero dependencies on file mounting.

**Comment by davidwindell** [comment]
:+1: for env var. This PR should also open up support for GitLab, Bitbucket etc.

**Comment by fermayo** [comment]
In any case, if you want to mount the SSH key file, you can do that without having to modify `run.sh`:

```
docker run \
  -v ~/.ssh/id_rsa:/root/.ssh/id_rsa \
  -e GIT_REPO=git@github.com:private/repo.git \
  -it --rm --privileged tutum/builder:staging ...
```

I have updated staging to store github.com's fingerprint in known_hosts, and updated the README.

**Pull request closed without merging**
