### PR TITLE
Fix #60 Use proper entrypoint override in the README.md

### LINKED ISSUE #60: Caching not working
I see we have in the docker file:
```VOLUME /var/lib/docker```
But if you follow the README and try to create a container as the cache

$ docker run --privileged --name builder_cache tutum/builder true
=> Starting docker
=> Checking docker daemon
=> Loading docker auth configuration
   WARNING: no $USERNAME/$PASSWORD or $DOCKERCFG found - unable to load any credentials for pushing/pulling
=> Detecting application
   ERROR: No application found in /app, and no $GIT_REPO defined

It seems that it still tries to build something. It seems the "true" at the end of the command is not used as a flag to say that I don't need to build anything.

### PR DESCRIPTION
**Pull request by sunshineo**
https://github.com/tutumcloud/builder/issues/60

### CODE REVIEW

**Comment by fermayo** [comment]
what about https://github.com/tutumcloud/builder/pull/65 ?

**Comment by sunshineo** [comment]
#65 clearly works. But does it worth introduce a separated image?

**Comment by fermayo** [comment]
Well, let's keep it simple, let's go with this. But remove the `--privileged` flag as it's not needed for the volume container

**Comment by sunshineo** [comment]
Removed and created https://github.com/tutumcloud/builder/pull/66

**Pull request closed without merging**
